### ISSUE TITLE
Inconsistent results of SDD matrix multiplication

### ISSUE THREAD

**Issue by salaniz** [ptillet/torch-blocksparse#16]
I have issues getting consistent results when applying SDD matrix multiplication several times with identical input matrices and sparse layout.

Code to reproduce:
```python
import sys

import torch
import torch_blocksparse

for i in range(20):
    block = 16
    Z, H, N, K = 1, 1, 256, 8
    a = torch.ones((Z, H, N, K), dtype=torch.float32).cuda()
    b = torch.ones((Z, H, N, K), dtype=torch.float32).cuda()
    a = a * float(K) ** -0.5

    layout = torch_blocksparse.attention.make_layout(H, N//block, 'fixed', 4, True, 1, 1)
    dot = torch_blocksparse.MatMul(layout, block, 'sdd', trans_a=False, trans_b=True)
    c = dot(a, b)
    print(c.mean().item(), c.std().item())

    # reload torch_blocksparse
    delkeys = [key for key in sys.modules.keys() if key.startswith('torch_blocksparse')]
    for k in delkeys:
        del sys.modules[k]
    import torch_blocksparse
```
Output:
```
3.524484634399414 1.2183359861373901
5.6422529220581055 0.28100723028182983
3.555734634399414 1.2999520301818848
4.933174133300781 1.234202265739441
5.702519416809082 0.7220494747161865
4.2408881187438965 1.4809025526046753
4.980049133300781 1.3033604621887207
4.933174133300781 1.234202265739441
4.278205871582031 1.6033270359039307
3.524484634399414 1.2183359861373901
4.980049133300781 1.3033604621887207
4.933174133300781 1.234202265739441
5.702519416809082 0.7220494747161865
5.6495771408081055 0.4620417654514313
5.702519416809082 0.7220494747161865
4.2408881187438965 1.4809025526046753
4.980049133300781 1.3033604621887207
5.6422529220581055 0.28100723028182983
3.555734634399414 1.2999520301818848
5.6422529220581055 0.28100723028182983
```

The above code is derived from your sparse multi-head attention implementation. Matrices `a` and `b` are initialized to fixed values and the layout is taken from the fixed sparse attention pattern. The code prints mean and standard deviation of the resulting sparse matrix which is expected to be the same in every run. Moreover, if I understand it correctly then I would expect the output to have no variation at all because all values in both matrices are the same.

The loop simulates several runs where I reload the torch_blocksparse library after each run. When the library is not reloaded then I still exhibit the behavior, however, I only encounter 2 distinct output values instead of arbitrary ones.

I haven't tried different variations of inputs and SDD configs.

Software environment:
- CUDA: 10.1
- PyTorch: 1.5.1
- torch-blocksparse: 1.0.4

**Comment by ptillet** [comment]
Hey!

First of all, thanks for giving a reproducible code snippet. In SDD, K must be a multiple of 16 in FP32 and 64 in FP16. I've just added error messages when this is not the case. Thanks for pointing this out.

**Comment by salaniz** [comment]
Thanks for the quick reply.
Indeed, this solves the issue.
