### ISSUE TITLE
Integer division problem

### ISSUE THREAD

**Issue by sparkdoc** [ptillet/torch-blocksparse#19]
https://github.com/ptillet/torch-blocksparse/blob/c368a9fd1b2c9dee4cc94de9a6bb0be3d447be41/torch_blocksparse/softmax.py#L339

When I ran the simple demo script, the following line caused an error:
```
# create object for Sparse = softmax(Sparse)
softmax = torch_blocksparse.Softmax(layout, block)
```
The error message was:

> ---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-5-26292ac51f93> in <module>
      1 # create object for Sparse = softmax(Sparse)
----> 2 softmax = torch_blocksparse.Softmax(layout, block)

~/anaconda3/envs/blocksparse/lib/python3.7/site-packages/torch_blocksparse/softmax.py in __init__(self, layout, block, bench)
    337     def __init__(self, layout, block, bench = False):
    338         self.num_blocks = layout.sum()
--> 339         self.num_blocks_per_head = self.num_blocks / layout.shape[0]
    340         self.spdims = layout.shape
    341         self.layout = layout

RuntimeError: Integer division of tensors using div or / is no longer supported, and in a future release div will perform true division as in Python 3. Use true_divide or floor_divide (// in Python) instead.

**Comment by ptillet** [comment]
Hey!

Thanks for reporting this issue. It should be fixed now (https://github.com/ptillet/torch-blocksparse/commit/beddcc3eda6d3df1b34f74c2e10139e4317d0e7f)
