### ISSUE TITLE
deprecated use of nonzero()

### ISSUE THREAD

**Issue by sparkdoc** [ptillet/torch-blocksparse#20]
When I call c = dot(a, b), I get the following deprecation warning:

> torch_blocksparse/matmul.py:519: UserWarning: This overload of nonzero is deprecated:
	nonzero()
Consider using one of the following signatures instead:
	nonzero(*, bool as_tuple) (Triggered internally at  /opt/conda/conda-bld/pytorch_1595629403081/work/torch/csrc/utils/python_arg_parser.cpp:766.)
  nnz = layout.nonzero()

>

**Comment by ptillet** [comment]
Thanks for reporting it. I've seen this warning a few times indeed. I will try to fix it in a few days.

**Comment by ptillet** [comment]
Fixed in 3c987c6fa3b
