### ISSUE TITLE
Timeline for support w/ latest Triton

### ISSUE THREAD

**Issue by tgale96** [ptillet/torch-blocksparse#38]
Hello!

I tried benchmarking some of these kernels on Ampere and it looks like this repo hasn't been updated to work with the latest version of Triton. Is there a version of Triton I should use (that includes Ampere support) that works with this repo? If not, do you have a rough timeline of when these kernels will be updated for A100?

Thanks!
Trevor

**Comment by ptillet** [comment]
Hi! You can use triton.ops.blocksparse in the main repo.  I will update the README torch-blocksparse, as it is deprecated.

**Comment by tgale96** [comment]
Ah great, thank you!
