### ISSUE TITLE
Can not install blocksparse

### ISSUE THREAD

**Issue by clevercool** [ptillet/torch-blocksparse#4]
When I run this instruction:
pip install -e "git+https://github.com/ptillet/triton.git#egg=triton&subdirectory=python"
And there is a problem:

> [ 92%] Building CXX object CMakeFiles/triton.dir/lib/lang/type.cc.o
    [ 94%] Building CXX object CMakeFiles/triton.dir/lib/runtime/arg.cc.o
    [ 96%] Building CXX object CMakeFiles/triton.dir/lib/runtime/function.cc.o
    [ 98%] Building CXX object CMakeFiles/triton.dir/python/src/bindings.cc.o
    /root/torch-blocksparse/torch_blocksparse/triton/python/src/bindings.cc: In function ‘std::tuple<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > make_tensorflow_src(const string&, const std::vector<std::__cxx11::basic_string<char> >&, const std::vector<std::__cxx11::basic_string<char> >&, const triton::runtime::function::options_space_t&)’:
    /root/torch-blocksparse/torch_blocksparse/triton/python/src/bindings.cc:411:26: error: converting to ‘std::tuple<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >’ from initializer list would use explicit constructor ‘constexpr std::tuple<_T1, _T2>::tuple(_U1&&, _U2&&) [with _U1 = std::__cxx11::basic_string<char>; _U2 = std::__cxx11::basic_string<char>&; <template-parameter-2-3> = void; _T1 = std::__cxx11::basic_string<char>; _T2 = std::__cxx11::basic_string<char>]’
       return {oss.str(), name};
                              ^
    /root/torch-blocksparse/torch_blocksparse/triton/python/src/bindings.cc: In function ‘std::tuple<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > make_torch_src(const string&, std::vector<triton::runtime::arg_type>)’:
    /root/torch-blocksparse/torch_blocksparse/triton/python/src/bindings.cc:601:26: error: converting to ‘std::tuple<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >’ from initializer list would use explicit constructor ‘constexpr std::tuple<_T1, _T2>::tuple(_U1&&, _U2&&) [with _U1 = std::__cxx11::basic_string<char>; _U2 = const std::__cxx11::basic_string<char>&; <template-parameter-2-3> = void; _T1 = std::__cxx11::basic_string<char>; _T2 = std::__cxx11::basic_string<char>]’
       return {oss.str(), name};
                              ^
    CMakeFiles/triton.dir/build.make:1334: recipe for target 'CMakeFiles/triton.dir/python/src/bindings.cc.o' failed
    make[2]: *** [CMakeFiles/triton.dir/python/src/bindings.cc.o] Error 1
    make[2]: *** Waiting for unfinished jobs....
    CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/triton.dir/all' failed
    make[1]: *** [CMakeFiles/triton.dir/all] Error 2
    Makefile:94: recipe for target 'all' failed
    make: *** [all] Error 2
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/root/torch-blocksparse/torch_blocksparse/triton/python/setup.py", line 111, in <module>
        zip_safe=False,
      File "/root/miniconda3/envs/bs/lib/python3.6/site-packages/setuptools/__init__.py", line 144, in setup
        return distutils.core.setup(**attrs)
      File "/root/miniconda3/envs/bs/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/root/miniconda3/envs/bs/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/root/miniconda3/envs/bs/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/root/miniconda3/envs/bs/lib/python3.6/site-packages/setuptools/command/develop.py", line 38, in run
        self.install_for_development()
      File "/root/miniconda3/envs/bs/lib/python3.6/site-packages/setuptools/command/develop.py", line 140, in install_for_development
        self.run_command('build_ext')
      File "/root/miniconda3/envs/bs/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/root/miniconda3/envs/bs/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/root/torch-blocksparse/torch_blocksparse/triton/python/setup.py", line 53, in run
        self.build_extension(ext)
      File "/root/torch-blocksparse/torch_blocksparse/triton/python/setup.py", line 87, in build_extension
        subprocess.check_call(['cmake', '--build', '.'] + build_args, cwd=self.build_temp)
      File "/root/miniconda3/envs/bs/lib/python3.6/subprocess.py", line 311, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j4']' returned non-zero exit status 2.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /root/miniconda3/envs/bs/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/root/torch-blocksparse/torch_blocksparse/triton/python/setup.py'"'"'; __file__='"'"'/root/torch-blocksparse/torch_blocksparse/triton/python/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.`

How can I fix it?

Thanks!

**Comment by ptillet** [comment]
Hi! I suspect it is just due to an older version of GCC and just pushed a patch that could solve the issue. Could you retry?

**Comment by clevercool** [comment]
Thanks, I successfully install on docker with CUDA 10.1 and GCC version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1). 
By the way,  is there any way to tell the program run on CUDA core or Tensor core?

**Comment by ptillet** [comment]
Yes, FP16 input should always run on tensor cores, or fail on a GPU that doesn't have tensor cores or has CUDA < 10.1. Please open a new issue if you encounter any issue using them -- they're not tested as heavily but should work :)
